# Vscode 安裝 REST Client

### GET /api/user - 取得所有使用者
GET http://localhost:3001/api/user

### GET /api/user/:id - 取得單一使用者
GET http://localhost:3001/api/user/1

### POST /api/user - 建立一個新的使用者
POST http://localhost:3001/api/user
Content-Type: application/json

{
  "username": "使用者",
  "is_active": true,
  "role": "normal"
}

### PUT /api/user/:id - 更新一個使用者
PUT http://localhost:3001/api/user/1
Content-Type: application/json

{
  "username": "更新使用者",
  "role": "admin"
}

### DELETE /api/user/:id - 刪除一個使用者
DELETE http://localhost:3001/api/user/2

### GET /api/auth
GET http://localhost:3001/api/auth/