# Vscode 安裝 REST Client
@baseUrl = http://localhost:1746/api
# @token = {{auth_token}}

### GET /api/user - 取得所有使用者
GET {{baseUrl}}/user

### GET /api/user/:id - 取得單一使用者
GET {{baseUrl}}/user/1

### POST /api/user - 建立一個新的使用者
POST {{baseUrl}}/user
Content-Type: application/json

{
  "username": "admin",
  "is_active": true,
  "role": "admin",
  "password": "admin"
}

### PUT /api/user/:id - 更新一個使用者
PUT {{baseUrl}}/user/1
Content-Type: application/json

{
  "username": "admin",
  "role": "admin",
  "password": "admin"
}

### DELETE /api/user/:id - 刪除一個使用者
DELETE {{baseUrl}}/user/2



### POST /api/login - 登入
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}